services:
  traefik:
    image: traefik:v3.3
    # container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certResolver=default"
      - "--entrypoints.websecure.http.tls.domains[0].main=${DOMAIN}"
      - "--log.level=DEBUG" # Set to DEBUG temporarily
      - "--accessLog=true"
      - "--accessLog.format=json"
      - "--accessLog.fields.defaultMode=keep"
      - "--accessLog.fields.headers.defaultMode=keep"
      - "--accessLog.fields.headers.names.Content-Security-Policy=drop"
      - "--accessLog.fields.headers.names.Permissions-Policy=drop"
      - "--api.insecure=${TRAEFIK_API_INSECURE:-true}"
      - "--api.dashboard=${TRAEFIK_DASHBOARD:-false}"
    ports:
      - "${TRAEFIK_HTTP_PORT:-80}:80"
      - "${TRAEFIK_HTTPS_PORT:-443}:443"
    security_opt:
      - no-new-privileges:true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .:/etc/traefik/dynamic:ro
      - ./certs:/certs:ro
    networks:
      - dev_rodent
    environment:
      - DOMAIN=${DOMAIN:-localhost}
      - SCHEME=${SCHEME:-http}
      - ENABLE_TLS=${ENABLE_TLS:-false}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost}

networks:
  dev_rodent:
    external: true
    name: dev_rodent_external
